# Generated by Django 4.2.3 on 2023-09-29 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kanban',
            old_name='status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='kanban',
            old_name='summary',
            new_name='Summary',
        ),
    ]
