# Generated by Django 4.2.3 on 2023-09-25 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
