# Generated by Django 4.2.3 on 2023-10-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='joined_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
