# Generated by Django 4.2.3 on 2023-10-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_clickinginstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickinginstance',
            name='x',
            field=models.DecimalField(decimal_places=10, max_digits=16),
        ),
        migrations.AlterField(
            model_name='clickinginstance',
            name='y',
            field=models.DecimalField(decimal_places=10, max_digits=16),
        ),
    ]
