# Generated by Django 4.2.3 on 2023-10-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_clickinginstance_x_alter_clickinginstance_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickinginstance',
            name='x',
            field=models.DecimalField(decimal_places=16, max_digits=20),
        ),
        migrations.AlterField(
            model_name='clickinginstance',
            name='y',
            field=models.DecimalField(decimal_places=16, max_digits=20),
        ),
    ]
