# Generated by Django 4.2.3 on 2023-10-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_clickinginstance_x_alter_clickinginstance_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickinginstance',
            name='pain_level',
            field=models.IntegerField(default=1),
        ),
    ]
