# Generated by Django 4.2.3 on 2023-10-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_clickinginstance_pain_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickinginstance',
            name='pain_level',
            field=models.IntegerField(),
        ),
    ]
