# Generated by Django 4.2.3 on 2023-10-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_alter_clickinginstance_pain_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='customer',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('E', 'Erkek'), ('K', 'Kadın')], max_length=1),
        ),
        migrations.AddField(
            model_name='customer',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='customer',
            name='tc_no',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='customer',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=3),
        ),
    ]
