# Generated by Django 4.2.3 on 2023-09-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='joined_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
